export enum IndustryType {
    SOFTWARE_IT_SERVICES = 'Software / IT Services',
    LOGISTICS_TRANSPORTATION = 'Logistics & Transportation',
    HEALTHCARE_MEDICAL = 'Healthcare & Medical',
    EDUCATION_E_LEARNING = 'Education & E-Learning',
    FINANCE_BANKING = 'Finance & Banking',
    RETAIL_E_COMMERCE = 'Retail & E-commerce',
    MANUFACTURING = 'Manufacturing',
    CONSTRUCTION_REAL_ESTATE = 'Construction & Real Estate',
    TELECOMMUNICATIONS = 'Telecommunications',
    AUTOMOTIVE = 'Automotive',
    HOSPITALITY_TOURISM = 'Hospitality & Tourism',
    MEDIA_ENTERTAINMENT = 'Media & Entertainment',
    ENERGY_UTILITIES = 'Energy & Utilities',
    LEGAL_SERVICES = 'Legal Services',
    MARKETING_ADVERTISING = 'Marketing & Advertising',
    NON_PROFIT_NOGS = 'Non-Profit & NGOs',
    AGRICULTURE_FARMING = 'Agriculture & Farming',
    GOVERNMENT_PUBLIC_SECTOR = 'Government & Public Sector',
    AEROSPACE_DEFENSE = 'Aerospace & Defense',
    PHARMACEUTICALS_BIOTECHNOLOGY = 'Pharmaceuticals & Biotechnology',
    FOOD_BEVERAGE = 'Food & Beverage',
    FASHION_APPAREL = 'Fashion & Apparel',
    CONSULTING_SERVICES = 'Consulting Services',
    INSURANCE = 'Insurance',
    OTHER = 'Other',
}